version: '3.8'

services:
  # Сервис Pushgateway
  gavrilova-va-netology-pushgateway:
    image: prom/pushgateway:latest
    container_name: gavrilova-va-netology-pushgateway
    ports:
      - "9091:9091"
    command:
      - '--web.listen-address=:9091'
      - '--persistence.file=/pushgateway/data'
    volumes:
      - pushgateway_data:/pushgateway/data
    networks:
      gavrilova-va-my-netology-hw:
        ipv4_address: 10.5.0.10
    restart: unless-stopped
    depends_on:
      - gavrilova-va-netology-prometheus

  # Сервис Prometheus
  gavrilova-va-netology-prometheus:
    image: prom/prometheus:latest
    container_name: gavrilova-va-netology-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      gavrilova-va-my-netology-hw:
        ipv4_address: 10.5.0.20
    restart: always
    depends_on:
      - gavrilova-va-netology-grafana

  # Сервис Grafana
  gavrilova-va-netology-grafana:
    image: grafana/grafana-oss:latest
    container_name: gavrilova-va-netology-grafana
    ports:
      - "80:3000"
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
      GF_SECURITY_ADMIN_USER: gavrilova-va
      GF_SECURITY_ADMIN_PASSWORD: netology
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/custom.ini:ro
    networks:
      gavrilova-va-my-netology-hw:
        ipv4_address: 10.5.0.30
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  prometheus_data:
    driver: local
  pushgateway_data:
    driver: local
  grafana_data:
    driver: local

networks:
  gavrilova-va-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

